name: Test workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::741448947753:role/github
          role-session-name: test
          aws-region: us-east-1

      - name: AWS command
        run: |
          aws s3 sync s3://huge-logistics-prod-mirror ./s3-data
      - name: Upload as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: s3-backup
          path: ./s3-data
          retention-days: 7  # optional, default is 90
